version: 2.1

jobs:
  test:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          command: |
            python -m pytest tests/test_triangle.py

  build:
    docker:
      - image: python:3.10
    depends_on:
      - test
    steps:
      - checkout
      - run:
          command: |
            python -m build