version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install pytest
            pip install pytest-cov
      - run:
          name: Run Tests with Coverage
          command: pytest --cov=src --cov-report=html tests/
      - store_artifacts:
          path: htmlcov

  GENERIC_JOB:
    docker:
      - image: python:3.8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run Generic Job
          command: |
            # Algoritmo do job generico, que será executado caso o teste do job "test" não falhe.

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - GENERIC_JOB:
          requires:
            - test
