version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install pytest
      - run:
          name: Run Tests
          command: pytest tests/
  
  build:
    docker:
      - image: python:3.8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build Production Code
          command: |
            # Insira aqui outros comandos que são necessários para executar a app, caso seja desejado.
            # No caso de linguagens que necessitam compilar, como C, seria interessante compilar e rodar neste job.
  
workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test
