version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install pytest
      - run:
          name: Run Tests
          command: pytest tests/
  
  build:
    docker:
      - image: python:3.8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build Production Code
          command: |
            # Add build steps for your production code here
            # For example:
            # python src/build.py
  
workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test
